### ISSUE TITLE
更新后开始按钮会触发分享，客服无法发送信息。

### ISSUE THREAD

**Issue by xianyi0119** [LearnTools123/learn#5]
您好，a3d404a更新后，蓝色开始按钮会触发分享功能，似乎是按钮叠加除了问题。
试图给客服发送信息，打完后没有发送按钮，手机键盘只能不断换行……
操作系统是华为。

**Comment by LearnTools123** [comment]
1. 按钮叠加的问题会在下个版本进行修复。

 联系客服的发送按钮，是否可以详细机型。

**Comment by xianyi0119** [comment]
> 1. 按钮叠加的问题会在下个版本进行修复。
> 
> 联系客服的发送按钮，是否可以详细机型。

华为荣耀9 操作系统版本EMUI9.1.0，辛苦

**Comment by LearnTools123** [comment]
已经修复。麻烦重新安装
