### ISSUE TITLE
图文教程链接打不开

### ISSUE THREAD

**Issue by wuwu955** [LearnTools123/learn#6]
<Error>
<Code>AccessDenied</Code>
<Message>You are denied by bucket referer policy.</Message>
<RequestId>61429EDB000B1F3934FF3287</RequestId>
<HostId>lanhu.oss-cn-beijing.aliyuncs.com</HostId>
<BucketName>lanhu</BucketName>
</Error>

**Comment by LearnTools123** [comment]
复制URL到浏览器进行查看
